name: deploy to ec2

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploys to ec2
        env:
          PRIVATE_KEY: ${{secrets.EC2_KEY}}
          HOST: ${{secrets.EC2Host}}
          USER: ${{secrets.EC2USER}}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '

          if ! command -v nvm &> /dev/null; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          fi
          nvm install 20

          if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          fi

          REPO_URL=https://github.com/hearjest/thegame.git
          BRANCH="master"
          REPO_DIR="$HOME/thegame"

          if [ -d "$REPO_DIR/.git" ]; then
            cd "$REPO_DIR"
            git pull origin "$BRANCH"
          else
            git clone "$REPO_URL" "$REPO_DIR"
            cd "$REPO_DIR"
          fi

          cd "$REPO_DIR"
          npm install

          cd "$REPO_DIR/server"

          echo "Start"
          pm2 restart server.ts || pm2 start server.ts
          '

